markdown: kramdown
title: Jadepond
tagline: Living the pondlife
theme: jekyll-theme-cayman
permalink: pretty

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  Jadepond is likely a waste of your time

# The base hostname & protocol of your site for where absolute urls are needed
url: https://jadepond.com

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Blog
  url: /blog/

# Author information - author info at the bottom of the post
author_name: "Sendmarsh"
author_bio: "A fairly insignificant person."
author_url: "https://jadepond.com"
author_location: "Berlin, Germany"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://jadepond.com/

# Footer newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
#github_username: "username"
#medium_username: "@username"
#instagram_username: "username"
#linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]



kramdown:
    auto_ids: false
